### ISSUE TITLE
File not found: animations/animations.atlas

### ISSUE THREAD

**Issue by ghost** [RoaringCatGames/libgdx-ashley-box2d-example#2]
It's missing a file needed to run. I'm still learning a lot looking through the code though, thanks for putting this out there!

**Comment by Barryrowe** [comment]
Make sure you run the texture packer before running

```
./gradlew texture-packer:run
```

**Comment by Barryrowe** [comment]
I have just updated the README "Running" section to clarify this. I think I used to have the texture-packer wired into the `desktop:run` target, but removed it to prevent unnecessary image packing. Thanks for the input. I'm going to close this out, but let me know if running the texture-packer doesn't resolve this and I'll open it back up.
